export enum Position {
  MANAGER = "MANAGER",
  CASHIER = "CASHIER",
  ASSISTANT_MANAGER = "ASSISTANT_MANAGER",
  OFFICER = "OFFICER",
  TELLER = "TELLER",
  SENIOR_OFFICER = "SENIOR_OFFICER",
  JUNIOR_OFFICER = "JUNIOR_OFFICER",
  ACCOUNTANT = "ACCOUNTANT",
  INTERN = "INTERN"
}
